### ISSUE TITLE
Failed to install 

### ISSUE THREAD

**Issue by peiyaoli** [wowchemy/hugo-academic-cli#84]
I tried to install the academic package as described in tutorial but get this error information: 

ERROR: Cannot uninstall 'ruamel-yaml'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

How to resolve this issue please?

**Comment by gcushen** [comment]
This error appears to be related to your system setup, rather than Academic itself.

See https://stackoverflow.com/questions/49932759/pip-10-and-apt-how-to-avoid-cannot-uninstall-x-errors-for-distutils-packages

You could also consider installing in virtual Python environment: https://realpython.com/pipenv-guide/
